---
name: "Test"
on:
  pull_request:
  push:
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
      - name: "Install requirements"
        run: |
          pip install -r requirements.txt
          pip install sphinxcontrib-spelling
      - name: "Run build test"
        run: |
          make test
      - name: "Check spelling"
        run: |
          sphinx-build -b spelling ./ _build/spelling
